language: python

python:
  - 2.7
  - 3.4

env:
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7

install:
  - pip install -q -e .
  - pip install django 

script: 
  - python setup.py test 
